name: Deploy Production

on:
  workflow_dispatch:

jobs:
  production:
      runs-on: ubuntu-latest
      name: Production
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
        - name: Build And Deploy on Production
          id: builddeploy
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_ROCK_077E5D410 }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: "upload"
            app_location: "/"
            app_build_command: "yarn run build-prod"
            output_location: "out"
